### ISSUE TITLE
Need help adding spawn points

### ISSUE THREAD

**Issue by Friebay** [Source2ZE/StripperCS2#2]
Hello.
Firstly, I would like to thank you for your amazing work.
I wanted to recreate the 2 players vs 20 bots game that I was on OhnePixel stream. I learnt how to set up CS2 servers on my own machine and now I am stuck on the part of adding spawn points. Using Source 2 Viewer on map de_inferno I found out that I need to add "info_player_terrorist". Following the template, I created a file `"default_ents.jsonc"` in `"C:\Users\user\Desktop\steamcmd\server\game\csgo\addons\StripperCS2\maps\de_inferno"`.
This is the content of the file:
```
{
    "add": [
        {
          "classname": "info_player_terrorist"
		  "io": [
          {
          "origin": "-1657.229980 439.576996 -46.000000",
		  "enabled": "True",
		  "priority": "0",
		  "targetname":"[PR#]spawnpoints.standard",
		  "angles": "<0, 358.5, 0>",
		  "scales": "1.000000 1.000000 1.000000",
		  "hammerUniqueId": "9999"}]
        }
    ]
}
```
This is my start.bat
```
cd "C:\Users\user\Desktop\steamcmd\server\game\bin\win64"
start /wait cs2.exe -dedicated -usercon -console -secure -dev +game_type 3 +game_mode 0 -maxplayers_override 64 +sv_logfile 1 -serverlogging +sv_setsteamaccount THATLONGCODE +map de_inferno +exec server.cfg
```
When the server starts, I run these commands: `mp_autoteambalance 0`, then `mp_limitteams 0`, then `bot_add_t` several times, but only the default 16 bots spawn. Additionally, I have installed the Metamod and CS2Fixes addons.
Any push in the right direction would be greatly appreciated.

**Comment by Frozen-H2O** [comment]
You are adding the entity improperly. io is only for entity Input/Output. KeyValues like origin, angles, etc. should be added in the same way you are adding the classname.
targetname also shouldnt be needed on a spawnpoint unless you have other entity io enabling/disabling the spawnpoint.
If you still don't understand from this explanation, here is an example of adding an invisible prop to block a skip in a map: https://github.com/gflze/CS2-ZE-Configs/blob/main/stripper/ze_emerald/default_ents.jsonc

**Comment by Friebay** [comment]
Thank you, the issue is now fixed.
If anyone else needs this feature, then this is how my `default_ents.jsonc` now looks. It adds 4 player spawns for each team in de_inferno.
```
{
    "add": [
        {
            "classname": "info_player_terrorist",
            "origin": "-1678.104614 21.132883 -46.386902",
            "enabled": "True",
			"priority": "0",
			"angles": "<0, 358.5, 0>",
            "scales": "1 1 1"
        },
		{
            "classname": "info_player_terrorist",
            "origin": "-1661.687744 136.950729 -46.213661",
            "enabled": "True",
			"priority": "0",
			"angles": "<0, 358.5, 0>",
            "scales": "1 1 1"
        },
		{
            "classname": "info_player_terrorist",
            "origin": "-1567.963013 344.348022 -46.469566",
            "enabled": "True",
			"priority": "0",
			"angles": "<0, 358.5, 0>",
            "scales": "1 1 1"
        },
		{
            "classname": "info_player_terrorist",
            "origin": "-1483.093750 101.724266 0.102844",  
            "enabled": "True",
			"priority": "0",
			"angles": "<0, 358.5, 0>",
            "scales": "1 1 1"
        },
		{
            "classname": "info_player_counterterrorist",
            "origin": "2379.958252 2272.432373 140.199982",
            "enabled": "True",
			"priority": "0",
			"angles": "<0, 358.5, 0>",
            "scales": "1 1 1"
        },
		{
            "classname": "info_player_counterterrorist",
            "origin": "2414.371582 2426.583008 140.539841",
            "enabled": "True",
			"priority": "0",
			"angles": "<0, 358.5, 0>",
            "scales": "1 1 1"
        },
		{
            "classname": "info_player_counterterrorist",
            "origin": "2283.452881 2443.559326 140",
            "enabled": "True",
			"priority": "0",
			"angles": "<0, 358.5, 0>",
            "scales": "1 1 1"
        },
		{
            "classname": "info_player_counterterrorist",
            "origin": "2172.730957 1853.605225 140.545685",  
            "enabled": "True",
			"priority": "0",
			"angles": "<0, 358.5, 0>",
            "scales": "1 1 1"
        }
		
    ]
}
```
I also added `mp_buy_anywhere "1"` to `server.cfg`, since not all added bots are in the buy zone and I don't know how to extend the buy zone borders.
edit: I probably could add another buy zone, but with scale of 2, but that would need some testing to do.
